/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcodec_JavaCodec */

#ifndef _Included_libcodec_JavaCodec
#define _Included_libcodec_JavaCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcodec_JavaCodec
 * Method:    codigo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcodec_JavaCodec_codigo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
